name: Create Release for siushin/util

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # 匹配 v1.0.0, v2.3.4 等语义化版本标签

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史记录，用于生成changelog

      - name: Generate Changelog
        run: |
          # 生成简版changelog
          git log --pretty=format:"- %s (%h)" $(git describe --tags --abbrev=0 @^)..@ > CHANGELOG.md
          echo "## Release Notes" >> CHANGELOG.md
          cat CHANGELOG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}